# See https://docs.rubocop.org/rubocop/configuration
Style/Encoding:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/StringLiterals:
  EnforcedStyle: double_quotes
Style/Documentation:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Style/MutableConstant:
  Enabled: false
