" Example Vim graphical configuration.
" Copy to ~/.gvimrc or ~/_gvimrc.

set guifont=Menlo:h11           " Font family and font size.
set antialias                   " MacVim: smooth fonts.
set encoding=utf-8              " Use UTF-8 everywhere.
set guioptions-=T               " Hide toolbar.
set guioptions-=r               " no right scroll
set guioptions-=l               " no left scroll
set guioptions-=L
set background=light            " Background.
set lines=25 columns=100        " Window dimensions.

highlight ColorColumn guibg=lightGrey 
