arch_name="$(uname -m)"

if [ "${arch_name}" = "x86_64" ]; then
  # add homebrew to path
  eval "$(/usr/local/bin/brew shellenv)"
  
  # load chruby
  source /usr/local/opt/chruby/share/chruby/chruby.sh
  source /usr/local/opt/chruby/share/chruby/auto.sh
elif [ "${arch_name}" = "arm64" ]; then
  # load chruby
  eval "$(/opt/homebrew/bin/brew shellenv)"
  
  # load chruby
  source /opt/homebrew/share/chruby/chruby.sh
  source /opt/homebrew/share/chruby/auto.sh
else
  echo "Unknown architecture: ${arch_name}"
fi

chruby $(cat ~/.ruby-version)

# aliases
alias lsl="pwd && ls -laGh"
alias bx="bundle exec"
alias gt="gittower"
alias start="heroku local:start -f Procfile.dev"

# bindings
bindkey "^[[A" history-beginning-search-backward
bindkey "^[[B" history-beginning-search-forward
