# load homebrew
eval "$(/opt/homebrew/bin/brew shellenv)"

# load chruby
source /opt/homebrew/share/chruby/chruby.sh
source /opt/homebrew/share/chruby/auto.sh

chruby $(cat ~/.ruby-version)

# add make binaries to path for some reason doesn't work on zshenv
export PATH="/opt/homebrew/opt/make/libexec/gnubin:$PATH"

# aliases
alias lsl="pwd && ls -laGh"
alias bx="bundle exec"
alias gt="gittower"
alias start="heroku local:start -f Procfile.dev"

# bindings
bindkey "^[[A" history-beginning-search-backward
bindkey "^[[B" history-beginning-search-forward
