export PATH="/Applications/Xcode.app/Contents/Developer/usr/bin:$PATH"
export HOMEBREW_GITHUB_API_TOKEN="$(cat $HOME/.github_token)"
export CDPATH=".:$HOME/Code"
export EDITOR="/usr/local/bin/nova"
export DISABLE_SPRING=true
