export PG_BIN="/usr/local/opt/postgresql@15/bin:/opt/homebrew/opt/postgresql@15/bin"
export PATH="/Applications/Xcode.app/Contents/Developer/usr/bin:$PG_BIN:$PATH"
export HOMEBREW_GITHUB_API_TOKEN="$(cat $HOME/.github_token)"
export BUNDLE_RUBYGEMS__PKG__GITHUB__COM="$(cat $HOME/.github_token)"
export CDPATH=".:$HOME/Code"
export EDITOR="/usr/local/bin/nova"
export DISABLE_SPRING=true
export RUBY_YJIT_ENABLE=true
